### ISSUE TITLE
Problems when generating docset from java 1.6 API doc

### ISSUE THREAD

**Issue by xingyunshisui** [Kapeli/javadocset#3]
Hi, I download an offline ziped java 1.6 API doc from -> http://download.java.net/jdk/jdk-api-localizations/jdk-api-zh-cn/publish/1.6.0/html_zh_CN.zip, use javadocset to generate Dash docset.

The docset is generated successfully, but with many warning like:
"
Warning: could not determine type for itemListener. Please tell the developer about this!

itemListener - 类 javax.swing.plaf.basic.BasicComboPopup 中的变量 and

Warning: could not determine type for ItemSelectable. Please tell the developer about this!

ItemSelectable - java.awt 中的 接口 and

Warning: could not determine type for itemStateChanged(ItemEvent). Please tell the developer about this!

itemStateChanged(ItemEvent) - 接口 java.awt.event.ItemListener 中的方法 and

Warning: could not determine type for iterator(). Please tell the developer about this!

iterator() - 异常 java.sql.SQLException 中的方法 and
"

The docset can be importer in Dash, but it just has few SQLite indexes, I'm not sure it's because of the warings above.

Thanks:)

**Comment by Kapeli** [comment]
This is because the docs are in Chinese. Javadocset looks inside the index files and looks for things like "Class in ..." (https://github.com/Kapeli/javadocset/blob/master/javadocset/DHIndexer.m#L63-L110), but in the docs these are in Chinese and not recognised.

There's nothing I can do. I don't want to support docs in other languages as it would be too much work.

If you want, you can fork this repo and translate the strings to Chinese to get it working.

**Comment by xingyunshisui** [comment]
OK, thank u~

**Comment by cxzl25** [comment]
@xingyunshisui 
Chinese Java SE6 API documentation support
https://github.com/cxzl25/javadocset/commit/e4b96daafeee53d3a2db273245e4907018824e89
